version: 2.1

orbs:
  android: circleci/android@2.5.0
  macos: circleci/macos@2

jobs:
  ios:
    macos:
      xcode: "15.4.0"
    resource_class: m4pro.medium
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - macos/switch-ruby:
          version: "3.3.0"
      - run:
          name: Install node/npm
          command: command -v node || brew install node
      - run:
          name: Install Cordova
          command: npm install -g cordova
      - run:
          name: Add iOS platform
          command: cd Example && cordova platform add ios@7.1.1
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build ios

  android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    environment:
      GRADLE_OPTS: -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=512m"  -Dorg.gradle.workers.max=2
    working_directory: ~/project/Example
    steps:
      - checkout
      - run:
          name: Accept all Android licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - run:
          name: Install Cordova
          command: npm install -g cordova
      - run:
          name: Add Android platform
          command: cd Example && cordova platform add android@15.0.0
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build android --verbose -- --gradleArg=--stacktrace

  publish:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > intercom-plugin/.npmrc
            npm config set scope $ORG_NAME
            cd intercom-plugin && npm publish

workflows:
  version: 2.1
  ios_and_android:
    jobs:
      - ios:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
      - android:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
      - publish:
          requires:
            - ios
            - android
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
