version: 2

jobs:
  ios:
    macos:
      xcode: "11.1.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install node/npm
          command: command -v node || brew install node
      - run:
          name: Install Cordova
          command: npm install -g cordova@9.0.0
      - run:
          name: Setup CocoaPods
          command: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run:
          name: Add iOS platform
          command: cd Example && cordova platform add ios
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build ios --buildFlag="-UseModernBuildSystem=0"

  android:
    docker:
      - image: circleci/android:api-28
    environment:
      - JVM_OPTS: -Xmx3200m
    working_directory: ~/project/Example
    steps:
      - checkout
      - run:
          name: Accept all Android licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - run:
          name: Install node/npm
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt install -y nodejs
      - run:
          name: Install gradle
          command: sudo apt-get install gradle
      - run:
          name: Install Cordova
          command: sudo npm install -g cordova@9.0.0
      - run:
          name: Add Android platform
          command: cd Example && cordova platform add android
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build android --verbose -- --gradleArg=--stacktrace

  publish:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: Install node/npm
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt install -y nodejs
      - run:
          name: Publish to npm
          command: |
            echo -e "$NPM_USER\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
            cd intercom-plugin && npm publish

workflows:
  version: 2
  ios_and_android:
    jobs:
      - ios:
          filters:
            tags:
              only: /[0-9](\.[0-9]+)+/
      - android:
          filters:
            tags:
              only: /[0-9](\.[0-9]+)+/
      - publish:
          requires:
            - ios
            - android
          filters:
            tags:
              only: /[0-9](\.[0-9]+)+/
            branches:
              ignore: /.*/
