version: 2

jobs:
  ios:
    macos:
      xcode: "13.4.1"
    resource_class: macos.x86.medium.gen2
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install node/npm
          command: command -v node || brew install node
      - run:
          name: Install Cordova
          command: npm install -g cordova
      - run:
          name: Add iOS platform
          command: cd Example && cordova platform add ios@latest
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build ios --buildFlag="-UseModernBuildSystem=0"

  android:
    docker:
      - image: circleci/android:api-30
    environment:
      - JVM_OPTS: -Xmx3200m
    working_directory: ~/project/Example
    steps:
      - checkout
      - run:
          name: Accept all Android licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - run:
          name: Install node/npm
          command: |
            curl -O https://packages.cloud.google.com/apt/doc/apt-key.gpg && sudo apt-key add apt-key.gpg
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt install -y nodejs
      - run:
          name: Install gradle
          command: sudo apt-get install gradle
      - run:
          name: Install Cordova
          command: sudo npm install -g cordova@9.0.0
      - run:
          name: Add Android platform
          command: cd Example && cordova platform add android@10.0.0
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build android --verbose -- --gradleArg=--stacktrace

  publish:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: Install node/npm
          command: |
            curl -O https://packages.cloud.google.com/apt/doc/apt-key.gpg && sudo apt-key add apt-key.gpg
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt install -y nodejs
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > intercom-plugin/.npmrc
            npm config set scope $ORG_NAME
            cd intercom-plugin && npm publish

workflows:
  version: 2
  ios_and_android:
    jobs:
      - ios:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
      - android:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
      - publish:
          requires:
            - ios
            - android
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/
